### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by Dorkside** [aothms/IfcOpenShell_CGAL#17]
Hi, landed here after finding your work on IFC conversion to citygml and can't find any info on whether this utility fills that usecase. More specifically the merge and simplification needed for efficient rendering. Read your papers BTW, great quality work. Helped me understand quite a bit.

**Comment by kenohori** [comment]
Hi James,
This is more of a test of a new approach to attempt to solve the problem, but we don't yet have a complete solution here. Thanks for the interest!

**Comment by Dorkside** [comment]
Hey, I understand this is experimental, and by far am not looking for anything perfect. Trying to figure out a way to do this for unreal engine at the moment. We know how to do it manually but it's a very time consuming matter. I've been trying some approaches based on boolean in multiple environments but they all seem to have the same limitations. Would love to know more and help if I can.
When you say not a complete solution, do you mean that on a simple ifc with structural elements only, you would obtain some kind of result? That would be awesome :angel:

**Comment by kenohori** [comment]
Well, the idea here is to swap IfcOpenShell's openCASCADE kernel with a new one based on CGAL. By doing this, every IFC object becomes a CGAL Nef polyhedron with which you can do Boolean ops, Minkowski sums and so on. Currently, the creation of CGAL Nef polyhedra works for most IFC objects, but there are still many issues we need to solve. In the medium term, we want to do conversions to CityGML as well as automated tests using this idea, but right now this is not yet implemented.

You can read more about the project here:
https://3d.bk.tudelft.nl/ken/files/18_geobim.pdf

You might also want to take a look here:
https://github.com/tudelft3d/ifc2citygml

**Comment by aothms** [comment]
> boolean in multiple environments but they all seem to have the same limitations

Exactly! The arbitrary precision kernel of CGAL would in principal enable arbitrary unions of all building elements, where other engines would encounter issues due to limited precision and compounding tolerance values.

> do you mean that on a simple ifc with structural elements only, you would obtain some kind of result

> Well, the idea here is to swap IfcOpenShell's openCASCADE kernel with a new one based on CGAL

This is the only effort currently undertaken. So even if you get a meaningful representation of IFC building elements as CGAL polyhedra, there is currently no procedure to union them and serialize those (admittedly that might be the more straightforward part though). At the moment this library just inherits the same executables as vanilla IfcOpenShell, which just serializes elements individually to for example OBJ.

> but there are still many issues we need to solve

And some of these are somewhat fundamental. I.e. that a lot of IFC geometries contain issues (such as self-intersections) that go undetected in plain BRep or triangular renderers. On the other hand though, note that these are typically in the elements of lesser significance (furniture, window frames, ...). Walls, slabs and openings are usually simple extrusions of polyhedral footprints that work rather well.


Long story short, if you want to have a look, there is a build script for Linux/OSX [1] that should get you close to a working environment. That will compile all dependencies from source. You can also use your package manager of course, look at the Travis CI script for references [2], but somehow I didn't manage to get it to work. @kenohori did really amazing work with the foundational effort to map IFC representations to CGAL polyhedra. If you want to invest time in approaching the issue from the other end to create unions of the polyhedra, I'd be happy to assist. I'm the author of the original Open CASCADE-based IfcOpenShell so I know the structure of the code rather well, but I'm embarrassingly unfamiliar with CGAL.

[1] https://github.com/aothms/IfcOpenShell_CGAL/tree/cgal/nix
[2] https://github.com/aothms/IfcOpenShell_CGAL/blob/cgal/.travis.yml
